### PR TITLE
Use relative redirect for /docs/

### PR DESCRIPTION
**Pull request by przmv**

### CODE REVIEW

**Comment by prees1** [comment]
Cool! And it works locally for you too?

**Comment by przmv** [comment]
Yes, but I haven't been using any complex configuration: nginx run on port 8080 inside docker container with 80:8080 mapping from host (i.e [host]localhost:80 → [docker]localhost:8080).

**Comment by prees1** [comment]
Ok great. The deployment for this is not via any CI/CD unfortunately. I'll give it a try locally and will document the steps on how to deploy as I do it. That way we all have the ability and as a guide to setup ci/cd.

**Comment by prees1** [comment]
@pshevtsov I've cloned and run `docker build -t swagger-ui .` and then went to start a container from the image. 
nginx complains of this:
image
Thoughts? I know you said you ran it via docker. Maybe I'm missing something obvious that I've forgotten.

Did you run via the Dockerfile in the repo or a different one?
The one in the file executed this during image build (in case it is a version issue):
image

**Comment by dcolebatch** [comment]
Looks like we need to bump the version of nginx there @pshevtsov 

From http://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect

> _This directive appeared in version 1.11.8._

**Comment by prees1** [comment]
There is a branch `pnr/patch-patch` that updates the nginx version.

With that change and using the docker file to build and run:

```
docker build -t swagger-ui .
docker run -p 80:8080 swagger-ui
```

and loading dev.localtest.me/docs/ redirects to -> http://dev.localtest.me:8080/docs/

Which I think is a problem because nginx is including the local container port of `8080` which won't work. WDYT?

**Comment by prees1** [comment]
🚀

**Pull request merged**
